(()=>{
  const link=document.createElement('link');link.rel='stylesheet';link.href='/product-demo.css';document.head.appendChild(link);
  const old=document.querySelector('.contract-section');if(!old)return;
  old.className='pdx-demo-section';old.id='au-product-explorer';
  old.innerHTML=`<div class="shell pdx-demo-wrap">
    <div class="pdx-head"><div><span class="pdx-kicker">CERTIFIED AUSTRALIA GRAPH EXPLORER</span><h2>See the normalization layer your team would otherwise have to build.</h2><p>Australia is eight jurisdiction systems underneath one product contract. This explorer shows the certified national identity spine and the state-native cadastral depth already promoted into PropData — without inventing a fake showcase property where an exact production canary has not been certified.</p></div><div class="pdx-head-actions"><a class="pdx-btn primary" href="/workspace">Open Australia Workspace →</a><a class="pdx-btn" href="/docs.html">Read the contract</a></div></div>
    <div class="pdx-browser" aria-label="PropData Australia certified country graph explorer">
      <div class="pdx-top"><div class="pdx-brand"><span class="pdx-live-dot"></span><b>PROPDATA AU</b><small>CERTIFIED COUNTRY GRAPH EXPLORER</small></div><div class="pdx-controls"><span class="pdx-badge">NATIONAL IDENTITY LIVE</span><button class="pdx-toggle active" data-pdx-view="parsed">PARSED</button><button class="pdx-toggle" data-pdx-view="json">JSON</button></div></div>
      <div class="pdx-tabs"><button class="active" data-pdx-route="national"><span>NATIONAL</span><small>G-NAF identity</small></button><button data-pdx-route="qld"><span>QUEENSLAND</span><small>QSCF cadastre</small></button><button data-pdx-route="vic"><span>VICTORIA</span><small>Vicmap cadastre</small></button><button data-pdx-route="tasact"><span>TAS + ACT</span><small>certified cadastre</small></button></div>
      <div class="pdx-request"><span class="pdx-method">GET</span><div class="pdx-url">/v1/property?country=AU&amp;address=<strong>&lt;Australian property&gt;</strong></div><span class="pdx-status"><i></i>COUNTRY CONTRACT · SOURCE-AWARE</span></div>
      <div class="pdx-pane active" data-pdx-pane="parsed"><div class="pdx-grid">
        <aside class="pdx-property"><div class="pdx-photo"><div class="pdx-shape"></div><div class="pdx-pin"></div><span class="pdx-photo-label">AUSTRALIA · NATIONAL PROPERTY GRAPH</span></div><div class="pdx-property-body"><div class="pdx-title-row"><div><span>COUNTRY CONTRACT</span><h3>AUSTRALIA</h3></div><b>CERTIFIED</b></div><p>A complete national G-NAF address spine plus promoted state-native cadastral layers. Identifiers, geometry and provenance remain jurisdiction-aware underneath one application contract.</p><div class="pdx-facts"><div><span>National addresses</span><b>16,970,406</b></div><div><span>Certified cadastre</span><b>7,052,719+</b></div><div><span>Cadastre live</span><b>4 jurisdictions</b></div><div><span>Country systems</span><b>8 jurisdictions</b></div></div></div></aside>
        <section class="pdx-panel"><div class="pdx-panel-head"><div><span id="pdx-route-label">NATIONAL PROPERTY IDENTITY</span><b id="pdx-route-title">One address spine. State-native depth beneath it.</b></div><span class="pdx-schema">COUNTRY-AWARE · SOURCE-NATIVE</span></div><div class="pdx-cards" id="pdx-cards"></div><div class="pdx-sourcebar"><div><span>NATIONAL IDENTITY</span><b>G-NAF · 2026-08 certified baseline</b></div><div><span>CADASTRE</span><b>State / territory source systems</b></div><div><span>NORMALIZATION</span><b>PropData country contract</b></div><div><span>GATING</span><b>Source + rights before promotion</b></div></div></section>
      </div></div>
      <div class="pdx-pane" data-pdx-pane="json"><div class="pdx-json"><div class="pdx-json-copy"><span>CERTIFIED COVERAGE SNAPSHOT</span><h3>One contract.<br>No fake uniformity.</h3><p>This view is a coverage snapshot, not a fabricated property response. Exact property fields are determined by the jurisdiction and source coverage returned for the resolved property.</p><a href="/docs.html">Inspect Australia semantics →</a></div><pre id="pdx-json"></pre></div></div>
      <div class="pdx-proof"><div><b>16.97M</b><span>national G-NAF addresses</span></div><div><b>7.05M+</b><span>certified cadastral records</span></div><div><b>4</b><span>cadastral jurisdictions live</span></div><div><b>NSW</b><span>next pinned-source promotion</span></div><div><b>8</b><span>jurisdictions · one contract</span></div></div>
    </div>
    <div class="pdx-bottom"><div><small>WHAT THIS PROVES</small><b>The product is the normalization layer: national address identity, state-native parcel systems, geometry, source revisions, jurisdiction semantics and controlled promotion behind one stable Australia integration.</b></div><div class="pdx-pills"><span>G-NAF</span><span>QSCF</span><span>Vicmap</span><span>LIST</span><span>ACT legal blocks</span><span>Provenance</span></div></div>
  </div>`;

  const data={
    national:{label:'NATIONAL PROPERTY IDENTITY',title:'One address spine. State-native depth beneath it.',cards:[['01','G-NAF ADDRESSES','16,970,406','Certified 2026-08 national baseline',''],['02','SOURCE PARTITIONS','9 / 9','National baseline reconciled',''],['03','CADASTRAL RECORDS','7,052,719+','Certified across four jurisdictions','blue'],['04','CADASTRE LIVE','QLD · VIC · TAS · ACT','State-native depth promoted','blue'],['05','COUNTRY SYSTEMS','8 jurisdictions','One country-aware application contract',''],['06','PROMOTION RULE','Source + rights gated','No unsupported jurisdiction claims','gold']],json:{country_code:'AU',coverage_snapshot:{national_address_spine:{source:'G-NAF',records:16970406,source_partitions:'9/9',baseline:'2026-08',status:'certified_complete'},certified_cadastre:{records:7052719,jurisdictions:['QLD','VIC','TAS','ACT']},next_promotion:'NSW',deeper_cadastre_gated:['WA','SA','NT']},contract_rule:'preserve jurisdiction-native identity and provenance'}},
    qld:{label:'QUEENSLAND CADASTRAL DEPTH',title:'A live state-native parcel foundation.',cards:[['01','QSCF PARCELS','2,156,480','Certified Queensland lot parcels',''],['02','STATUS','LIVE','Production cadastral baseline',''],['03','GEOMETRY','Polygon depth','State-native parcel geometry','blue'],['04','IDENTITY','Native lot IDs','Jurisdiction identifiers preserved',''],['05','ADDRESS SPINE','G-NAF national','Property identity connects to national addresses','blue'],['06','PROVENANCE','Queensland source','Source context retained downstream','']],json:{country_code:'AU',jurisdiction:'QLD',cadastre:{source:'QSCF',records:2156480,status:'live_certified',geometry:'state-native polygons'},national_identity:{source:'G-NAF',status:'complete'}}},
    vic:{label:'VICTORIA CADASTRAL DEPTH',title:'Vicmap is already inside the production graph.',cards:[['01','VICMAP RECORDS','4,303,714','Certified Victorian parcel records',''],['02','STATUS','LIVE','Production cadastral baseline',''],['03','IDENTIFIERS','PFI / UFI','Native identity retained',''],['04','GEOMETRY','Statewide','Parcel / property polygons','blue'],['05','SOURCE','State of Victoria','Provenance remains attached',''],['06','CONTRACT','country=AU','Same application surface as other states','blue']],json:{country_code:'AU',jurisdiction:'VIC',cadastre:{source:'Vicmap Property',records:4303714,status:'live_certified',native_identifiers:['PFI','UFI'],geometry:'statewide'},provenance:'State of Victoria'}},
    tasact:{label:'TASMANIA + ACT CERTIFIED DEPTH',title:'Smaller jurisdictions still keep their own semantics.',cards:[['01','TASMANIA','439,539','Certified LIST cadastral parcels',''],['02','ACT','152,986','Certified legal blocks',''],['03','COMBINED','592,525','Certified records across both','blue'],['04','TAS SOURCE','LIST','Tasmania cadastral system',''],['05','ACT MODEL','Legal blocks','Territory-native identity preserved',''],['06','OTHER STATES','WA · SA · NT','National address identity live; deeper cadastre gated','gold']],json:{country_code:'AU',jurisdictions:{TAS:{source:'LIST',records:439539,status:'live_certified'},ACT:{records:152986,model:'legal_blocks',status:'live_certified'}},gated_cadastral_depth:['WA','SA','NT']}}
  };
  const cards=old.querySelector('#pdx-cards'),label=old.querySelector('#pdx-route-label'),title=old.querySelector('#pdx-route-title'),json=old.querySelector('#pdx-json');
  const render=key=>{const r=data[key];label.textContent=r.label;title.textContent=r.title;cards.innerHTML=r.cards.map((c,i)=>`<article><div class="pdx-card-top"><span>${c[0]}</span><b class="pdx-state ${c[4]}">${c[4]==='gold'?'GATED':i===0?'CERTIFIED':'COVERED'}</b></div><small>${c[1]}</small><strong>${c[2]}</strong><p>${c[3]}</p></article>`).join('');json.textContent=JSON.stringify(r.json,null,2)};render('national');
  old.querySelectorAll('[data-pdx-route]').forEach(btn=>btn.addEventListener('click',()=>{old.querySelectorAll('[data-pdx-route]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');render(btn.dataset.pdxRoute)}));
  old.querySelectorAll('[data-pdx-view]').forEach(btn=>btn.addEventListener('click',()=>{old.querySelectorAll('[data-pdx-view]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');old.querySelectorAll('[data-pdx-pane]').forEach(p=>p.classList.toggle('active',p.dataset.pdxPane===btn.dataset.pdxView))}));
})();
